"""empty message

Revision ID: 40f8d0a5021b
Revises: 5212c3b7a516
Create Date: 2022-12-05 00:37:48.454350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f8d0a5021b'
down_revision = '5212c3b7a516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('recipes', 'title',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
