"""empty message

Revision ID: 5212c3b7a516
Revises: 
Create Date: 2022-11-29 11:07:40.465378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5212c3b7a516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_author_id', sa.Integer(), nullable=True),
    sa.Column('preview_image', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('steps', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_author_id', sa.Integer(), nullable=True),
    sa.Column('note_recipe_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['note_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['note_recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('recipes')
    op.drop_table('users')
    # ### end Alembic commands ###
